"""Append 18 continuous reading groups, without replacing prior research data."""
from append_v04_batch6 import main

ROWS = [
('communism',13,'男女关系与人的退化',
'In dem Verhältniß zum Weib, als dem Raub und d[er] Magd der gemeinschaftlichen Wollust, ist die unendliche Degradation ausgesprochen, in welcher der Mensch für sich selbst existirt, denn das Geheimniß dieses Verhältnisses hat seinen unzweideutigen, entschiednen, offenbaren, enthüllten Ausdruck in dem Verhältnisse des Mannes zum Weibe und in der Weise, wie das unmittelbare, natürliche Gattungsverhältniß gefaßt wird.',
'把妇女当作共同淫欲的掳获物和婢女来对待，这表现了人在对待自身方面的无限的退化，因为这种关系的秘密在男人对妇女的关系上，以及在对直接的、自然的类关系的理解方式上，都毫不含糊地、确凿无疑地、明显地、露骨地表现出来。',[388],[321]),
('communism',14,'自然的类关系与人的本质',
'Das unmittelbare, natürliche, nothwendige Verhältniß d[es] Menschen zum Menschen ist das Verhältniß des Mannes zum Weibe. // In diesem natürlichen Gattungsverhältniß ist das Verhältniß des Menschen zur Natur unmittelbar sein Verhältniß zum Menschen wie das Verhältniß zum Menschen unmittelbar sein Verhältniß zur Natur, seine eigne natürliche Bestimmung ist. In diesem Verhältniß erscheint also sinnlich, auf ein anschaubares Factum reducirt inwieweit dem Menschen das menschliche Wesen zur Natur oder die Natur zum menschlichen Wesen d[es] Menschen geworden ist.',
'人对人的直接的、自然的、必然的关系是男人对妇女的关系。在这种自然的类关系中，人对自然的关系直接就是人对人的关系，正像人对人的关系直接就是人对自然的关系，就是他自己的自然的规定。因此，这种关系通过感性的形式，作为一种显而易见的事实，表现出人的本质在何种程度上对人来说成为自然，或者自然在何种程度上成为人具有的人的本质。',[388],[321]),
('communism',15,'关系与文化教养程度',
'Aus diesem Verhältniß kann man also die ganze Bildungsstufe d[es] Menschen beurtheilen. | / Aus dem Charakter dieses Verhältnisses—folgt, inwieweit der Mensch als Gattungswesen, als Mensch sich geworden ist und erfaßt hat; das Verhältniß des Mannes zum Weib ist das natürlichste Verhältniß d[es] Menschen zum Menschen.',
'因此，从这种关系就可以判断人的整个文化教养程度。从这种关系的性质就可以看出，人在何种程度上对自己来说成为并把自身理解为类存在物、人。男人对妇女的关系是人对人最自然的关系。',[388],[321]),
('communism',16,'人的自然与人的需要',
'In ihm zeigt sich also inwieweit das natürliche Verhalten des Menschen menschlich oder inwieweit das menschlichenresen ihm zum Natürlichen Wesen, inwieweit seine menschliche Natur ihm zur Natur geworden ist. In diesem Verhältniß zeigt sich auch, inwieweit das Bedürfniß des Menschen zum menschlichen Bedürfniß, inwieweit ihm also der andre Mensch als Mensch zum Bedürfniß geworden ist, inwieweit er in seinem individuellsten Dasein zugleich Gemeinwesen ist.',
'因此，这种关系表明人的自然的行为在何种程度上成为人的行为，或者，人的本质在何种程度上对人来说成为自然的本质，他的人的本性在何种程度上对他来说成为自然。这种关系还表明，人具有的需要在何种程度上成为人的需要，就是说，别人作为人在何种程度上对他来说成为需要，他作为个人的存在在何种程度上同时又是社会存在物。',[388],[321,322]),
('communism',17,'粗陋共产主义的表现形式',
'Die erste positive Aufhebung des Privateigenthums, der rohe Communismus ist also nur eine Erscheinungsform von der Niedertracht des Privateigenthums, das sich als das positive Gemeinwesen setzen will.',
'由此可见，对私有财产的最初的积极的扬弃，即粗陋的共产主义，不过是想把自己设定为积极的共同体的私有财产的卑鄙性的一种表现形式。',[388],[322]),
('communism',18,'政治性质与废除国家',
'2) Der Communismus α) noch politischer Natur, demokratisch oder despotisch; ß) mit Aufhebung des Staats, aber zugleich noch unvollendetes, immer noch mit dem Privateigenthum, d. h. der Entfremdung d[es] Menschen afficirtem Wesen.',
'(2)共产主义(α)还具有政治性质，是民主的或专制的；(β)是废除国家的，但同时是还未完成的，总还是处于私有财产即人的异化的影响下。',[389],[322]),
('communism',19,'复归与尚未理解的本质',
'In beiden Formen weiß sich der Communismus schon als Reintegration oder Rückkehr des Menschen in sich, als Aufhebung der menschlichen Selbstentfremdung, aber indem er das positive Wesen des Privateigenthums noch nicht || erfaßt hat und ebensowenig die menschliche Natur des Bedürfnisses verstanden hat, ist er auch noch von demselben befangen und inf icirt. Er hat zwar seinen Begriff erfaßt, aber noch nicht sein Wesen.',
'这两种形式的共产主义都已经认识到自己是人向自身的还原或复归，是人的自我异化的扬弃；但是，因为它还没有理解私有财产的积极的本质，也还不了解需要所具有的人的本性，所以它还受私有财产的束缚和感染。它虽然已经理解私有财产这一概念，但是还不理解它的本质。',[389],[322]),
('communism',20,'对人的本质的真正占有',
'3) Der Communismus als positive Aufhebung des Privateigenthums, als menschlicher Selbstentfremdung und darum als wirkliche Aneignung des menschlichen Wesens durch und für d[en] Menschen; darum als vollständige, bewußt und innerhalb des ganzen Reichthums der bisherigen Entwicklung gewordne Rückkehr des Menschen für sich als eines gesellschaftlichen, d.h. menschlichen Menschen.',
'(3)共产主义是私有财产即人的自我异化的积极的扬弃，因而是通过人并且为了人而对人的本质的真正占有；因此，它是人向自身、向社会的即合乎人性的人的复归，这种复归是完全的，自觉的和在以往发展的全部财富的范围内生成的。',[389],[322]),
('communism',21,'自然主义与人道主义',
'Dieser Communismus ist als vollendeter Naturalismus = Humanismus, als vollendeter Humanismus = Naturalismus, er ist die wahrhafte Auflösung des Widerstreits des Menschen mit der Natur und mit d[em] Menschen, die wahre Auflösung des Streits zwischen Existenz und Wesen, zwischen Vergegenständlichung und Selbstbestätigung, zwischen Freiheit und Nothwendigkeit, zwischen Individuum und Gattung. Er ist das aufgelöste Räthsel der Geschichte und weiß sich als diese Lösung. /',
'这种共产主义，作为完成了的自然主义=人道主义，而作为完成了的人道主义=自然主义，它是人和自然界之间、人和人之间的矛盾的真正解决，是存在和本质、对象化和自我确证、自由和必然、个体和类之间的斗争的真正解决。它是历史之谜的解答，而且知道自己就是这种解答。⁹⁸',[389],[322]),
('communism',22,'历史运动与共产主义的生成',
'|V| Die ganze Bewegung der Geschichte ist daher, wie sein wirklicher Zeugungsakt — der Geburtsakt seines empirischen Daseins—so auch für sein denkendes Bewußtsein die begriffne und gewußte Bewegung seines Werdens, während jener noch unvollendete Communismus aus einzelnen dem Privateigenthum entgegenstehenden Geschichtsgestalten einen historischen Beweis, einen Beweis in dem Bestehenden für sich sucht, indem er einzelne Momente aus der Bewegung (Cabet, Villegardelle, etc reiten besonders auf diesem Roß) herausreißt und als Beweise seiner historischen Vollblütigkeit fixirt, womit er eben darthut, daß die unverhältnißmässig grössere Parthie dieser Bewegung seinen Behauptungen widerspricht und daß, wenn er einmal gewesen ist, eben sein vergangnes Sein die Prätention des Wesens widerlegt.',
'[V]因此，历史的全部运动，既是它的现实的产生活动——它的经验存在的诞生活动，——同时，对它的思维着的意识来说，又是它的被理解和被认识到的生成运动。而上述尚未完成的共产主义从各个与私有财产相对立的历史形式中为自己寻找历史的证明——在持续存在中的证明，同时它从运动中抽出个别环节（卡贝、维尔加德尔等人尤其喜欢卖弄这一套），把它们作为自己是历史的纯种的证明固定下来；但是，它这样做恰好说明：历史运动的绝大部分是同它的论断不一致的，如果它曾经存在过，那么它的这种过去的存在恰恰反驳了对本质的奢求。',[389],[322,323]),
('communism',23,'革命运动的基础',
'Daß in der Bewegung des Privateigenthums, eben d[er] Oekonomie, die ganze revolutionaire Bewegung sowohl ihre empirische, als theoretische Basis findet, davon ist die Nothwendigkeit leicht einzusehn.',
'不难看到，整个革命运动必然在私有财产的运动中，即在经济的运动中，为自己既找到经验的基础，也找到理论的基础。',[389],[323]),
('communism',24,'私有财产与人的生命',
'Das materielle, unmittelbar sinnliche Privateigenthum, ist der materielle sinnliche Ausdruck des entfremdeten menschlichen Lebens. Seine Bewegung — die Production und Consumtion — ist die sinnliche Offenbarung von der Bewegung aller bisherigen Production, d. h. Verwirklichung oder Wirklichkeit d[es] Menschen.',
'这种物质的、直接感性的私有财产，是异化了的人的生命的物质的、感性的表现。私有财产的运动——生产和消费——是迄今为止全部生产的运动的感性展现，就是说，是人的实现或人的现实。',[389,390],[323]),
('communism',25,'生产的特殊方式与异化的扬弃',
'Religion, Familie, Staat, Recht, Moral, Wissenschaft, Kunst etc sind nur besondre Weisen der Production und fallen unter ihr allgemeines Gesetz. Die positive Aufhebung des Privateigenthums als die Aneignung des menschlichen Lebens, ist daher die positive Aufhebung aller Entfremdung, also die Rückkehr des Menschen aus Religion, Familie, Staat etc in sein menschliches d. h. gesellschaftliches Dasein.',
'宗教、家庭、国家、法、道德、科学、艺术等等，都不过是生产的一些特殊的方式，并且受生产的普遍规律的支配。因此，对私有财产的积极的扬弃，作为对人的生命的占有，是对一切异化的积极的扬弃，从而是人从宗教、家庭、国家等等向自己的人的存在即社会的存在的复归。',[390],[323]),
('communism',26,'宗教异化与现实生活',
'Die religiöse Entfremdung als solche geht nur in dem Gebiet des Bewußtseins, des menschlichen Innern vor, aber die ökonomische Entfremdung ist die des wirklichen Lebens, — ihre Aufhebung umfaßt daher beide Seiten. Es versteht sich, daß die Bewegung bei den verschiednen Völkern ihren ersten Beginn danach nimmt, ob das wahre anerkannte Leben des Volkes mehr im Bewußtsein oder in der äussern Welt vorsichgeht, mehr das ideelle oder reelle Leben ist.',
'宗教的异化本身只是发生在意识领域、人的内心领域中，而经济的异化是现实生活的异化，——因此对异化的扬弃包括两个方面。不言而喻，在不同的民族那里，运动从哪个领域开始，这要看一个民族的真正的、公认的生活主要是在意识领域中还是在外部世界中进行，这种生活更多地是观念的生活还是现实的生活。',[390],[323]),
('communism',27,'无神论与共产主义的博爱',
'Der Communismus beginnt sogleich (Owen) mit dem Atheismus, der Atheismus ist zunächst noch weit entfernt Communismus zu sein, wie jener Atheismus mehr noch eine Abstraktion ist.—Die Philanthropie das Atheismus ist daher zuerst nur eine || philosophische abstrakte Philanthropie, die des Communismus sogleich reell und unmittelbar zur Wtkung gespannt.',
'共产主义是径直从无神论开始的（欧文）⁹⁹，而无神论最初还根本不是共产主义；那种无神论主要还是一个抽象。——因此，无神论的博爱最初还只是哲学的、抽象的博爱，而共产主义的博爱则径直是现实的和直接追求实效的。——',[390],[323]),
('communism',28,'人与对象的相互存在',
'Wir haben gesehn, wie unter Voraussetzung des positiv aufgehobnen Privateigenthums, der Mensch d[en] Menschen producirt, sich selbst und den andern Menschen; wie der Gegenstand, welcher die unmittelbare Bethätigung seiner Individualität zugleich sein eignes Dasein für den andern Menschen dessen Dasein und dessen Dasein für ihn ist.',
'我们已经看到，在被积极扬弃的私有财产的前提下，人如何生产人——他自己和别人；直接体现他的个性的对象如何是他自己为别人的存在，同时是这个别人的存在，而且也是这个别人为他的存在。',[390],[323]),
('communism',29,'材料与主体作为出发点',
'Ebenso sind aber sowohl das Material der Arbeit, als der Mensch als Subjekt, wie Resultat so Ausgangspunkt der Bewegung (und daß sie dieser Ausgangspunkt sein müssen, eben darin liegt die geschichthche Nothwendigkeit des Privateigenthums).',
'但是，同样，无论是劳动的材料还是作为主体的人，都既是运动的结果，又是运动的出发点（并且二者必须是这个出发点，私有财产的历史必然性就在于此）。',[390],[323,326]),
('communism',30,'社会性质与活动享受',
'Also ist der gesellschaftliche Charakter der allgemeine Charakter der ganzen Bewegung; wie die Gesellschaft selbst den Menschen als Menschen producirt, so ist sie durch ihn producirt. Die Thätigkeit und der Genuß, wie ihrem Inhalt, sind auch der Existenzweisenachgesellschaftliche Thätigkeit und gesellschaftlicher Genuß.',
'因此，社会性质是整个运动的普遍性质；正像社会本身生产作为人的人一样，社会也是由人生产的。活动和享受，无论就其内容或就其存在方式来说，都是社会的活动和社会的享受。',[390],[326]),
]

if __name__ == '__main__':
    main(rows=ROWS, printed={('de_megai2',388):'388',('de_megai2',389):'389',
         ('de_megai2',390):'390',('zh_collected',321):'296',('zh_collected',322):'297',
         ('zh_collected',323):'298',('zh_collected',326):'301'},
         batch=12, release='0.4.0-alpha8', reviewed_date='2026-10-04',
         doubts={'communism_de_016':['menschlichenresen'],
                 'communism_de_018':['ß)'], 'communism_de_019':['inf icirt'],
                 'communism_de_027':['das Atheismus','Wtkung'],
                 'communism_de_029':['geschichthche'],
                 'communism_de_030':['Existenzweisenachgesellschaftliche']},
         issue_overrides={'communism_de_018':{'ß)':dict(kind='glyph_doubt',status='open',
             reported_reading='分项标记ß/β字形待核',
             note='PDF389分项标记暂按可见提取候选ß)照录；ß与希腊β的字形区别待核，中文β独立照录，不据译文定字。')}},
         extra_page_maps=[dict(source_id='zh_collected',pdf_page=324,printed_page=None,
             page_kind='illustration',status='scan_checked_ai',checked_by='Codex',checked_at='2026-10-04',
             note='扫描图像为笔记本III第5页的手稿影印及图题，无印刷页标签；不推算为299。'),
             dict(source_id='zh_collected',pdf_page=325,printed_page=None,
             page_kind='blank',status='scan_checked_ai',checked_by='Codex',checked_at='2026-10-04',
             note='扫描图像无正文、图题或印刷页标签，仅见纸面及扫描边缘；不推算为300。')])
